version: "3.5"

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - WEB_CONCURRENCY=0
      - RAILS_MAX_THREADS=10
      - PORT=3001
      - DB_HOSTNAME=db
      - RINHA_DE_BACKEND_DATABASE_PASSWORD=postgres
      - RAILS_MASTER_KEY=e6b1e1bd647883d4e9a2ee298c45b0e3
    depends_on:
      - db
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "130MB"

  api02:
    <<: *api
    environment:
      - WEB_CONCURRENCY=2
      - RAILS_MAX_THREADS=5
      - PORT=3002
      - DB_HOSTNAME=db
      - RINHA_DE_BACKEND_DATABASE_PASSWORD=postgres
      - RAILS_MASTER_KEY=e6b1e1bd647883d4e9a2ee298c45b0e3
    depends_on:
      - api01 # Sometimes api dos not runs because rails db:prepare
    ports:
      - "3002:3002"
    hostname: api02
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "220MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100MB"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=rinha_de_backend
      - POSTGRES_DATABASE=rinha_de_backend_production
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "100MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
